Fix compilation error in bi-1.sql caused by implicit cast from int to float
java.lang.RuntimeException: [97.41] failure: Expected ']'

DECLARE MAP PERCENTAGEOFMESSAGES(float)[PC_CNT:float]

                                        ^
	at scala.sys.package$.error(package.scala:27)
	at ddbt.frontend.M3Parser$.apply(Parsers.scala:277)
	at ddbt.frontend.M3Parser$.apply(Parsers.scala:131)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at ddbt.Compiler$.compile(Compiler.scala:216)
	at ddbt.Compiler$.main(Compiler.scala:395)
	at ddbt.Compiler.main(Compiler.scala)